title: "Javani Research Lab"
description: "Research in nanophotonics, scientific AI, quantum computing, and cybersecurity."
url: "https://javani.org"
baseurl: ""
markdown: kramdown
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
